services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.12-alpine
    environment:
      CLICKHOUSE_USER: chuser
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: chpassword
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: wget --spider --tries 1 http://chuser:chpassword@clickhouse:8123/ping
      start_period: 30s
      start_interval: 1s
      timeout: 1s

  gateway:
    image: tensorzero/gateway
    volumes:
      # Mount your config directory into the container
      - ./config:/app/config:ro
    command: --config-file /app/config/tensorzero.toml
    environment:
      TENSORZERO_CLICKHOUSE_URL: "https://clickhouse-cloud-url-here"
      OPENAI_API_KEY: "sk-your-openai-api-key-here"
      NVIDIA_API_KEY: "nvapi-your-nvidia-api-key-here"
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - clickhouse
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      start_period: 1s
      start_interval: 1s
      timeout: 1s

  ui:
    image: tensorzero/ui
    volumes:
      # Mount your config directory into the container
      - ./config:/app/config:ro
    environment:
      TENSORZERO_CLICKHOUSE_URL: "https://clickhouse-cloud-url-here"
      TENSORZERO_GATEWAY_URL: "http://gateway:3000"
    ports:
      - "4000:4000"
    depends_on:
      - gateway
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4000/health",
        ]
      start_period: 1s
      start_interval: 1s
      timeout: 1s
